// One-off: turn a plain list of food-place names into geocoded seed data for the Map screen.
// Looks each name up via Mapbox Geocoding v6 (forward), biased to Indonesia + a city you pass,
// and writes src/data/seedPlaces.ts. The app's "Import our spots" button then upserts them.
//
// Usage:
//   MAPBOX_TOKEN=pk.xxx node scripts/geocode-places.mjs --city "Jakarta Selatan" --in scratch/places.json
//
// places.json may be either:
//   ["Kopi Tuku Cipete", "Sushi Tei Senopati"]                      (plain names)
//   [{ "name": "Kopi Tuku", "area": "Cipete" }]                     (name + its own area)
// --city is the default area folded into the query + note when a row has no `area`.
import { readFileSync, writeFileSync } from 'node:fs'

const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, a, i, arr) => {
    if (a.startsWith('--')) acc.push([a.slice(2), arr[i + 1]])
    return acc
  }, []),
)
const TOKEN = process.env.MAPBOX_TOKEN || process.env.VITE_MAPBOX_TOKEN
const CITY = args.city || ''
const INPUT = args.in
const OUT = args.out || 'src/data/seedPlaces.ts'

const useMapbox = Boolean(TOKEN)
if (!INPUT) {
  console.error('Missing --in <file.json>. Pass a JSON array of names (or {name,area} objects).')
  process.exit(1)
}
console.log(`Geocoding via ${useMapbox ? 'Mapbox' : 'Photon (keyless)'}${CITY ? ` · default city: ${CITY}` : ''}\n`)

const raw = JSON.parse(readFileSync(INPUT, 'utf8'))
const rows = raw.map((r) => (typeof r === 'string' ? { name: r, area: CITY } : { name: r.name, area: r.area || CITY }))

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

// Home-city bias (Medan). Keep in sync with HOME_CENTER in src/lib/geo.ts.
const HOME = { lat: '3.5952', lng: '98.6722' }

async function geocodeMapbox(q) {
  const url = new URL('https://api.mapbox.com/search/geocode/v6/forward')
  url.search = new URLSearchParams({
    q,
    access_token: TOKEN,
    country: 'id',
    language: 'id',
    proximity: `${HOME.lng},${HOME.lat}`,
    types: 'poi,address',
    limit: '1',
  }).toString()
  const res = await fetch(url)
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  const f = (await res.json()).features?.[0]
  if (!f) return null
  const p = f.properties ?? {}
  const lng = p.coordinates?.longitude ?? f.geometry?.coordinates?.[0]
  const lat = p.coordinates?.latitude ?? f.geometry?.coordinates?.[1]
  return Number.isFinite(lat) && Number.isFinite(lng)
    ? { lat, lng, address: p.full_address || p.place_formatted || undefined }
    : null
}

async function geocodePhoton(q) {
  const url = new URL('https://photon.komoot.io/api/')
  url.search = new URLSearchParams({ q, limit: '1', lat: HOME.lat, lon: HOME.lng }).toString()
  const res = await fetch(url)
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  const f = (await res.json()).features?.[0]
  if (!f) return null
  const [lng, lat] = f.geometry?.coordinates ?? []
  const p = f.properties ?? {}
  const address = [p.street, p.district, p.city, p.state, p.country].filter(Boolean).join(', ') || undefined
  return Number.isFinite(lat) && Number.isFinite(lng) ? { lat, lng, address } : null
}

async function geocode({ name, area }) {
  const q = [name, area].filter(Boolean).join(', ')
  const hit = useMapbox ? await geocodeMapbox(q) : await geocodePhoton(q)
  return hit ? { name, area, ...hit } : null
}

const out = []
const failed = []
for (const row of rows) {
  try {
    const place = await geocode(row)
    if (place) {
      out.push(place)
      console.log(`✓ ${row.name} → ${place.lat.toFixed(5)}, ${place.lng.toFixed(5)}`)
    } else {
      failed.push(row.name)
      console.warn(`✗ no match: ${row.name}`)
    }
  } catch (e) {
    failed.push(row.name)
    console.warn(`✗ ${row.name}: ${e.message}`)
  }
  await sleep(120) // be polite to the API
}

const body =
  `// Geocoded starter food spots, imported on first tap of "Import our spots" on the Map screen.\n` +
  `// GENERATED by scripts/geocode-places.mjs — re-run to regenerate. Edit the source list, not this.\n` +
  `import type { PlaceImport } from '../db/repo'\n\n` +
  `export const SEED_PLACES: PlaceImport[] = ${JSON.stringify(out, null, 2)}\n`
writeFileSync(OUT, body)

console.log(`\nWrote ${out.length} places to ${OUT}.`)
if (failed.length) console.log(`Could not geocode ${failed.length}: ${failed.join(', ')}`)
