// Geocoded starter food spots, imported on first tap of "Import our spots" on the Map screen.
// GENERATED by scripts/geocode-places.mjs from the couple's list + city — empty until that's run.
import type { PlaceImport } from '../db/repo'

export const SEED_PLACES: PlaceImport[] = []
